### ISSUE TITLE
Doesn't Work With Recent MessageFormat Updates

### ISSUE THREAD

**Issue by iammerrick** [gushov/grunt-messageformat#4]
Simply doesn't work anymore. See: https://github.com/SlexAxton/messageformat.js/issues/38

**Comment by jokeyrhyme** [comment]
Any chance of a pull-request? Is there anything you need help with?

**Comment by jokeyrhyme** [comment]
I ended up just using [grunt-exec](https://www.npmjs.org/package/grunt-exec) to run `messageformat` CLI directly.

**Comment by iammerrick** [comment]
That works but requires messageformat be installed globally. (Or referenced relatively.) I really want npm to implement `bundle exec` style functionality.

**Comment by jokeyrhyme** [comment]
Yeah, I installed `messageformat` locally (yuck, I know).

My grunt-exec configuration looks like:

```
exec: {
  messageformat: {
    cmd: 'node_modules/messageformat/bin/messageformat.js -l en js/locales/en js/locales/en/i18n.js'
  }
},
```

Kinda' terrible, but it works for me for now. I agree, about `npm exec`, that would be awesome:
- https://github.com/npm/npm/pull/4554
- https://github.com/npm/npm/pull/2460
- https://github.com/npm/npm/issues/1543

**Comment by alex-dow** [comment]
this project seems dead unfortunately. I have started a new one at https://github.com/alex-dow/grunt-messageformat-compiler

**Comment by jokeyrhyme** [comment]
Has anyone already looked at either of the following libraries as a replacement for this project?
- http://formatjs.io/
- http://i18next.com/
- https://github.com/jquery/globalize

How do they compare to this project? Which of these is the easiest to migrate to?

If no-one has any experience with these, I'll try to do a comparison myself in the next few weeks and see how it goes.

**Comment by alex-dow** [comment]
While I'm not aware of any formal comparisons to any of these projects, I can explain my rationale for wanting to stick close to MessageFormat:

i18next has a translation UI, a nice JSON structure, including support for multiline strings that are stored in arrays. Unfortunately, i18next does not use the ICU standard syntax. Since my webapp will also have a backend component to it written in Java and using ICU4J, I'd rather stick with the more common standard.

FormatJS is robust, has direct integrations with some popular frameworks, and does use MessageFormat and thus uses ICU standards. However, it relies on the [http://www.ecma-international.org/ecma-402/1.0/index.html](ECMA-402). Only IE11 fully supports this standard. Polyfills exist, but I'd prefer to avoid using them when possible.

Globalize has dependency overhead. This is something I appreciate about MessageFormat. It compiles your string resource files into small snippets of javascript that have no dependencies on anything at all. This makes integration into existing code painless, and has the least amount of overhead.

These are just my opinions really, and I have not done extensive research into any of those tools. But I still find that MessageFormat provides client-side localization with the lowest footprint and widest browser support (without resorting to polyfills).

**Comment by jokeyrhyme** [comment]
@alex-dow great points, very useful. Thanks.
